/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestionviajes;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author zapju
 */
public class VentanaInicio extends javax.swing.JFrame {
    static boolean cerrar = false;
    
    /**
     * Creates new form VentanaInicio
     */
    public VentanaInicio() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImageIcon icon = new ImageIcon(getClass().getResource("/images/fondo.png"));
        Image image = icon.getImage();
        escritorio = new javax.swing.JDesktopPane(){
            public void paintComponent(Graphics g){
                g.drawImage(image,0,0,getWidth(),getHeight(),this);
            }

        };
        jMenuBar1 = new javax.swing.JMenuBar();
        jmenuViaje = new javax.swing.JMenu();
        jmenuViajes = new javax.swing.JMenuItem();
        jmenuCliente = new javax.swing.JMenu();
        jmenuRegistroCliente = new javax.swing.JMenuItem();
        jmenuTaxista = new javax.swing.JMenu();
        jmenuRegistrarTaxi = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1069, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 616, Short.MAX_VALUE)
        );

        jMenuBar1.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N

        jmenuViaje.setText("Viaje");
        jmenuViaje.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        jmenuViajes.setText("Asignar Viajes");
        jmenuViajes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenuViajesActionPerformed(evt);
            }
        });
        jmenuViaje.add(jmenuViajes);

        jMenuBar1.add(jmenuViaje);

        jmenuCliente.setText("Cliente");
        jmenuCliente.setFocusable(false);
        jmenuCliente.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jmenuCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenuClienteActionPerformed(evt);
            }
        });

        jmenuRegistroCliente.setText("Lista de Clientes");
        jmenuRegistroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenuRegistroClienteActionPerformed(evt);
            }
        });
        jmenuCliente.add(jmenuRegistroCliente);

        jMenuBar1.add(jmenuCliente);

        jmenuTaxista.setText("Taxista");
        jmenuTaxista.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        jmenuRegistrarTaxi.setText("Lista de Taxistas");
        jmenuRegistrarTaxi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenuRegistrarTaxiActionPerformed(evt);
            }
        });
        jmenuTaxista.add(jmenuRegistrarTaxi);

        jMenuBar1.add(jmenuTaxista);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmenuRegistroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenuRegistroClienteActionPerformed
        // TODO add your handling code here:
        ListaClientes cliente = new ListaClientes();
        escritorio.add(cliente);
        cliente.show();
    }//GEN-LAST:event_jmenuRegistroClienteActionPerformed

    private void jmenuRegistrarTaxiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenuRegistrarTaxiActionPerformed
        // TODO add your handling code here:
        ListarTaxista taxista = new ListarTaxista();
        escritorio.add(taxista);
        taxista.show();
    }//GEN-LAST:event_jmenuRegistrarTaxiActionPerformed

    private void jmenuClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenuClienteActionPerformed
        //TODO add your handling code here:
        
    }//GEN-LAST:event_jmenuClienteActionPerformed

    private void jmenuViajesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenuViajesActionPerformed
        // TODO add your handling code here:
        AsignarViaje viajes = new AsignarViaje();
        escritorio.add(viajes);
        viajes.show();
    }//GEN-LAST:event_jmenuViajesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jmenuCliente;
    private javax.swing.JMenuItem jmenuRegistrarTaxi;
    private javax.swing.JMenuItem jmenuRegistroCliente;
    private javax.swing.JMenu jmenuTaxista;
    private javax.swing.JMenu jmenuViaje;
    private javax.swing.JMenuItem jmenuViajes;
    // End of variables declaration//GEN-END:variables
}
